export const demoTickets = [
  {
    id: "demo-0185",
    code: "E170-2025-0185",
    unit: "護理部",
    applicantName: "林護理師",
    roleType: "護理",
    ext: "2211",
    purpose: "校院活動",
    category: "海報輸出",
    status: "PENDING",
    assignedToName: null,
  },
  {
    id: "demo-0183-int",
    code: "E170-2025-0183",
    unit: "內科",
    applicantName: "陳醫師",
    roleType: "內科",
    ext: "4503",
    purpose: "教學研究",
    category: "平面設計",
    status: "PENDING",
    assignedToName: null,
  },
  {
    id: "demo-0182-int",
    code: "E170-2025-0182",
    unit: "內科",
    applicantName: "李醫師",
    roleType: "內科",
    ext: "4505",
    purpose: "校院活動",
    category: "數位攝影",
    status: "IN_PROGRESS",
    assignedToName: "設計師 蔡OO",
  },
  {
    id: "demo-0184-nursing",
    code: "E170-2025-0184-N",
    unit: "護理部",
    applicantName: "徐護理師",
    roleType: "護理",
    ext: "2218",
    purpose: "衛教宣導",
    category: "平面設計",
    status: "PENDING",
    assignedToName: null,
  },
  {
    id: "demo-0177",
    code: "E170-2025-0177",
    unit: "護理部",
    applicantName: "林護理師",
    roleType: "護理",
    ext: "2211",
    purpose: "衛教宣導",
    category: "數位攝影",
    status: "WAITING_REPLY",
    assignedToName: "設計師 蔡OO",
  },
  {
    id: "demo-0176-int",
    code: "E170-2025-0176",
    unit: "內科",
    applicantName: "張醫師",
    roleType: "內科",
    ext: "4507",
    purpose: "醫學發表",
    category: "海報輸出",
    status: "WAITING_REPLY",
    assignedToName: "設計師 黃OO",
  },
  {
    id: "demo-0175",
    code: "E170-2025-0175",
    unit: "護理部",
    applicantName: "王護理師",
    roleType: "護理",
    ext: "2216",
    purpose: "衛教宣導",
    category: "數位攝影",
    status: "IN_PROGRESS",
    assignedToName: "設計師 蔡OO",
  },
  {
    id: "demo-0174",
    code: "E170-2025-0174",
    unit: "內科",
    applicantName: "李醫師",
    roleType: "內科",
    ext: "4505",
    purpose: "校院活動",
    category: "數位攝影",
    status: "IN_PROGRESS",
    assignedToName: "設計師 李OO",
  },
  ...Array.from({ length: 40 }, (_, index) => {
    const isNursing = index % 2 === 0;
    const nursingApplicants = ["林護理師", "王護理師", "徐護理師"];
    const internalApplicants = ["陳醫師", "張醫師", "李醫師"];
    const applicantPool = isNursing ? nursingApplicants : internalApplicants;
    return {
      id: `demo-01${70 - index}`,
      code: `E170-2025-${String(1670 - index).padStart(4, "0")}`,
      unit: isNursing ? "護理部" : "內科",
      applicantName: applicantPool[index % applicantPool.length],
      roleType: isNursing ? "護理" : "內科",
      ext: isNursing ? "2211" : "4501",
      purpose: index % 3 === 0 ? "校院活動" : "醫學發表",
      category: isNursing ? "海報輸出" : "平面設計",
      status: "DONE",
      assignedToName: isNursing ? "設計師 蔡OO" : "設計師 李OO",
    };
  }),
];
